name: Release Workflow

on:
  push:
    tags:
      - 'gorelease*' # trigger on push tags matching regex

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang_dummy/
    strategy:
      matrix:
        go-version: ['1.21']
        # go-version: ['1.21', '1.21.x' ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "PACKAGE_NAME=${PWD##*/}" >> "$GITHUB_ENV"
      # - name: Name of resulting binary named from working directoory
        # run: echo "${{github.repository}}, ${{ github.workspace }}"
      - run: echo "${{env.PACKAGE_NAME}}"

      # - name: Setup Go ${{ matrix.go-version }}
        # uses: actions/setup-go@v4
        # with:
          # go-version: ${{ matrix.go-version }}
          # cache-dependency-path: go.sum
          # cache: false
      # - name: Display Go version
        # run: go version
      # - name: Test
      #   run: go test -v ./...
      # - name: build package with bash script
      #   run: ./scripts/build.sh
      # - name: Debug pwd
      #   run: pwd
      # - name: Debug list files
        # run: ls -laR

      # - name: Create Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       README.md
      #       ./golang_dummy/golang_dummy.bin
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     body: |
      #       Release created automatically
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
