name: main

on:
  push:
    tags:
      - 'gorelease_alt1' # Trigger only on tags that start with 'v'
  # push:
    # branches:
      # - main
      # - feature* 
      # - refactor*
  # pull_request:
    # branches:
      # - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache-dependency-path: go.sum

      - name: Build
        run: |
          sudo apt-get install -y libxml2-dev pkg-config
          go build -v ./...

      - name: Lint
        run: go vet -v ./...

      - name: Test
        run: go test

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        # if: matrix.os == 'ubuntu-latest'
